# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MigrateUrfaveCliV3 < Formula
  desc "Migrate github.com/urfave/cli/v2 to v3
"
  homepage "https://github.com/suzuki-shunsuke/migrate-urfave-cli-v3"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/migrate-urfave-cli-v3/releases/download/v0.1.0/migrate-urfave-cli-v3_darwin_amd64.tar.gz"
      sha256 "37c6386857333158d0f0150d7163264082cb1c51aa207332297bc685355c50b7"

      def install
        bin.install "migrate-urfave-cli-v3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/migrate-urfave-cli-v3/releases/download/v0.1.0/migrate-urfave-cli-v3_darwin_arm64.tar.gz"
      sha256 "cc9c0720afe27573e6b9757ef7e8365ec84c3d67a509d98d1529a6e5f7a4d293"

      def install
        bin.install "migrate-urfave-cli-v3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/migrate-urfave-cli-v3/releases/download/v0.1.0/migrate-urfave-cli-v3_linux_amd64.tar.gz"
        sha256 "844fe957876066785dc73f9cd269e8dcb076869231eb43aa5c714bf75a5af923"

        def install
          bin.install "migrate-urfave-cli-v3"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/migrate-urfave-cli-v3/releases/download/v0.1.0/migrate-urfave-cli-v3_linux_arm64.tar.gz"
        sha256 "08d736d25f43bbb10bc74f9f628e791df0e4cf26b488bf91da74d047b60a06d9"

        def install
          bin.install "migrate-urfave-cli-v3"
        end
      end
    end
  end

  test do
    system "#{bin}/migrate-urfave-cli-v3 --version"
  end
end
